import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Image from "next/image";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <header>
          <div className='gnb'>
            <div className='logos'>
              <h1>
                <Link href = "/">
                  <Image src="/img/logoBlocksmith.png" alt="BlockSmithLogo" width={166} height={26}/>
                </Link>
              </h1>

              <div>
                <Link href="/">홈</Link>
              </div>
            </div>

            <div className='Personal'>
              <div><Link href="/">공지</Link></div>
              <div>알림</div>
              <div>내 정보</div>
            </div>

        


          </div>
        </header>

        {children}</body>
    </html>
  )
}
